name: Install
description: "Installs dependencies with pnpm"
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 11.25.0
    - name: Install
      shell: bash
      run: pnpm install --frozen-lockfile
