name: Install
description: "Installs and caches node_modules"

runs:
  using: "composite"
  steps:
    - name: Restore node_modules cache
      id: node-modules-cache
      uses: actions/cache/restore@v4
      with:
        path: ./**/node_modules
        key: node-modules|${{ hashFiles( 'bun.lockb', 'package.json', '{apps,packages}/*/package.json' ) }}

    - name: Install
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      shell: bash
      run: bun install --no-save

    - name: Save node_modules cache
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ./**/node_modules
        key: node-modules|${{ hashFiles( 'bun.lockb', 'package.json', '{apps,packages}/*/package.json' ) }}
