stages:
  - test
  - release

test:
  image: node:16.20.0-alpine
  stage: test
  script:
    - yarn install
    - yarn lint
    - yarn test:coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

release:
  image: node:16.20.0-alpine
  stage: release
  script:
    - yarn install
    - yarn run release
  only:
    - master
