stages:
  - test
  - publish

test with coverage:
  image: node:16.20.0-alpine
  stage: test
  script:
    - yarn install
    - yarn lint
    - yarn test:coverage

publish:
  image: node:16.20.0-alpine
  stage: publish
  script:
    - yarn install
    - yarn run publish
  only:
    - master
