name: Test

on:
  workflow_call:
  push:
    branches-ignore:
      - master

defaults:
  run:
    shell: bash

env:
  TURBO_LOG_ORDER: stream

jobs:
  deploy:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/setup@v2
        with:
          cache: true

      - name: Fix versions
        run: pnpm run versions:fix

      - name: Cache turbo
        uses: actions/cache@v5
        with:
          path: .turbo/cache
          key: turbo|test|test|${{ github.sha }}
          restore-keys: turbo|test|

      - name: Run test:unit
        run: pnpm run test:unit
