name: Test & Release

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  TURBO_LOG_ORDER: stream
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  test:
    name: "Test"
    uses: ./.github/workflows/test.yml

  release:
    name: "Release"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version-file: package.json }

      - name: Install
        uses: ./.github/workflows/actions/install

      - name: Fix versions
        run: yarn run versions:fix

      - name: Cache turbo
        uses: actions/cache@v4
        with:
          path: .turbo/cache
          key: turbo|release|${{ github.sha }}
          restore-keys: turbo|release|

      - name: Release
        run: yarn run release
